language: generic
dist: bionic


install:
  # Newer tools
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # spell
  - apt-cache search spell
  - sudo apt install spell
  # proselint
  - sudo pip install proselint
  # pandoc
  - sudo apt install pandoc 
  # imagemagick
  - sudo apt install imagemagick
  # PDF creation
  - sudo apt install texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended texlive-extra-utils texlive-humanities texlive-full texlive-games texlive-pictures texlive-science texlive-xetex ktikz
  # PDF manipulation
  - sudo apt install qpdf
  # R
  - sudo apt install r-base-core r-cran-readr r-cran-stringr r-cran-testthat r-cran-ape
  # No: pgf

script:
  - make
  - if [ ! -f thesis.pdf ]; then echo "file 'thesis.pdf' not found" ; exit 1 ; fi

after_failure:
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

after_success:
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

