#!/bin/bash
#
# By default, the LaTeX tables generated by the pirouette examples 
# do not have a LaTeX label. This script adds these.
#
# Usage:
#
#   ./add_labels_to_pirouette_tables.sh
#
# Input files:
#
# * pirouette_example_30/example_30/*.latex
#
# Output files:
#
# * pirouette_example_30/example_30_314/*.latex
#
#
#
mkdir pirouette_example_30/example_30_314

sed '/\\caption{.*}/a \\\label{tab:esses_true_gen}' \
  pirouette_example_30/example_30/esses_gen.latex > \
  pirouette_example_30/example_30_314/esses_gen.latex

sed '/\\caption{.*}/a \\\label{tab:esses_true_best}' \
  pirouette_example_30/example_30/esses_best.latex > \
  pirouette_example_30/example_30_314/esses_best.latex

sed '/\\caption{.*}/a \\\label{tab:esses_twin_gen}' \
  pirouette_example_30/example_30/esses_twin_gen.latex > \
  pirouette_example_30/example_30_314/esses_twin_gen.latex

sed '/\\caption{.*}/a \\\label{tab:esses_twin_best}' \
  pirouette_example_30/example_30/esses_twin_best.latex > \
  pirouette_example_30/example_30_314/esses_twin_best.latex

sed '/\\caption{.*}/a \\\label{tab:true_evidence}' \
  pirouette_example_30/example_30/evidence_true.latex > \
  pirouette_example_30/example_30_314/evidence_true.latex

sed '/\\caption{.*}/a \\\label{tab:twin_evidence}' \
  pirouette_example_30/example_30/evidence_twin.latex > \
  pirouette_example_30/example_30_314/evidence_twin.latex

