#!/bin/bash

pdflatex dissertation
#bibtex dissertation
bibtex introduction/introduction
bibtex babette_article/article/article
bibtex pirouette_article/content
bibtex razzo_article/content
bibtex raket_article/content
pdflatex dissertation
pdflatex dissertation

# Also an option:
#
#   pdflatex dissertation --shell-escape
#
#
