#!/bin/bash

pdflatex dissertation
bibtex dissertation
#bibtex babette_article/article/article
pdflatex dissertation
pdflatex dissertation

#pdflatex thesis.tex --shell-escape
#bibtex thesis.aux
#pdflatex thesis.tex --shell-escape
#pdflatex thesis.tex --shell-escape
